import type { Coupon, Customer, Order, Product, Review } from "./types";
import { localAssets } from "./localAssets";

export const heroSlides = [
  {
    title: "Alaira Half Saree House",
    eyebrow: "Crafted For Grace",
    description:
      "Premium half sarees shaped for modern celebrations, soft drapes, and heirloom detail.",
    image: localAssets.wedding.url,
  },
  {
    title: "Silk With A Modern Glow",
    eyebrow: "New arrivals",
    description:
      "Kanjivaram, Mysore silk, and Tussar pieces curated for graceful everyday luxury.",
    image: localAssets.silk.url,
  },
  {
    title: "Festive Drapes, Quiet Finish",
    eyebrow: "Party wear",
    description:
      "Lightweight festive sarees with refined shimmer, clean borders, and fluid movement.",
    image: localAssets.party.url,
  },
];

export const mockProducts: Product[] = [
  {
    _id: "p1",
    title: "Kanjivaram Silk Bridal Saree",
    price: 8500,
    discountPrice: 6999,
    discount: 18,
    category: "Wedding Sarees",
    fabric: "Pure Silk",
    occasion: "Wedding",
    color: "Red",
    images: [localAssets.wedding, localAssets.silk],
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    stock: 12,
    rating: 4.8,
    reviews: 124,
    isNew: false,
    isBestSeller: true,
    description:
      "Handwoven Kanjivaram silk saree with intricate gold zari work. Perfect for bridal wear and grand celebrations.",
  },
  {
    _id: "p2",
    title: "Banarasi Georgette Party Saree",
    price: 4200,
    discountPrice: 3299,
    discount: 21,
    category: "Party Wear",
    fabric: "Georgette",
    occasion: "Party",
    color: "Blue",
    images: [localAssets.party, localAssets.silk],
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    stock: 25,
    rating: 4.6,
    reviews: 89,
    isNew: true,
    isBestSeller: false,
    description:
      "Elegant Banarasi georgette saree with subtle shimmer, ideal for evening parties and celebrations.",
  },
  {
    _id: "p3",
    title: "Cotton Handloom Daily Wear Saree",
    price: 1200,
    discountPrice: 999,
    discount: 17,
    category: "Daily Wear",
    fabric: "Cotton",
    occasion: "Casual",
    color: "Green",
    images: [localAssets.daily, localAssets.cotton],
    video: null,
    stock: 50,
    rating: 4.4,
    reviews: 210,
    isNew: false,
    isBestSeller: true,
    description:
      "Soft and breathable handloom cotton saree. Perfect for daily office or casual wear.",
  },
  {
    _id: "p4",
    title: "Designer Chiffon Festival Saree",
    price: 3500,
    discountPrice: 2799,
    discount: 20,
    category: "Party Wear",
    fabric: "Chiffon",
    occasion: "Festival",
    color: "Yellow",
    images: [localAssets.party, localAssets.wedding],
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    stock: 18,
    rating: 4.7,
    reviews: 67,
    isNew: true,
    isBestSeller: false,
    description:
      "Light and flowy chiffon saree with designer embroidery borders. Perfect for festivals.",
  },
  {
    _id: "p5",
    title: "Pure Mysore Silk Saree",
    price: 6800,
    discountPrice: 5499,
    discount: 19,
    category: "Silk Sarees",
    fabric: "Pure Silk",
    occasion: "Wedding",
    color: "Purple",
    images: [localAssets.silk, localAssets.wedding],
    video: null,
    stock: 8,
    rating: 4.9,
    reviews: 156,
    isNew: false,
    isBestSeller: true,
    description:
      "Authentic Mysore silk saree with classic temple border design. A timeless piece.",
  },
  {
    _id: "p6",
    title: "Linen Printed Office Saree",
    price: 1800,
    discountPrice: 1499,
    discount: 17,
    category: "Daily Wear",
    fabric: "Linen",
    occasion: "Office",
    color: "White",
    images: [localAssets.daily, localAssets.cotton],
    video: null,
    stock: 35,
    rating: 4.3,
    reviews: 92,
    isNew: false,
    isBestSeller: false,
    description:
      "Professional linen saree with subtle prints. Great for office and formal occasions.",
  },
  {
    _id: "p7",
    title: "Embroidered Net Bridal Saree",
    price: 12000,
    discountPrice: 9999,
    discount: 17,
    category: "Wedding Sarees",
    fabric: "Net",
    occasion: "Wedding",
    color: "Maroon",
    images: [localAssets.wedding, localAssets.party],
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    stock: 5,
    rating: 4.9,
    reviews: 43,
    isNew: true,
    isBestSeller: true,
    description:
      "Heavily embroidered net saree with stone work. The ultimate bridal statement piece.",
  },
  {
    _id: "p8",
    title: "Tussar Silk Ethnic Saree",
    price: 3200,
    discountPrice: 2599,
    discount: 19,
    category: "Silk Sarees",
    fabric: "Tussar Silk",
    occasion: "Ethnic",
    color: "Orange",
    images: [localAssets.silk, localAssets.daily],
    video: null,
    stock: 22,
    rating: 4.5,
    reviews: 78,
    isNew: false,
    isBestSeller: false,
    description:
      "Natural Tussar silk with earthy tones and artisanal prints. A unique ethnic choice.",
  },
  {
    _id: "p9",
    title: "Patola Print Cotton Saree",
    price: 2200,
    discountPrice: 1799,
    discount: 18,
    category: "Cotton Sarees",
    fabric: "Cotton",
    occasion: "Casual",
    color: "Pink",
    images: [localAssets.cotton, localAssets.daily],
    video: null,
    stock: 40,
    rating: 4.4,
    reviews: 134,
    isNew: true,
    isBestSeller: false,
    description:
      "Patola pattern printed cotton saree. Vibrant colors with comfortable daily wear fabric.",
  },
  {
    _id: "p10",
    title: "Organza Pearl Border Saree",
    price: 5400,
    discountPrice: 4499,
    discount: 17,
    category: "Party Wear",
    fabric: "Organza",
    occasion: "Reception",
    color: "Ivory",
    images: [localAssets.party, localAssets.wedding],
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    stock: 16,
    rating: 4.7,
    reviews: 58,
    isNew: true,
    isBestSeller: true,
    description:
      "Airy organza saree with pearl-inspired border work, made for receptions and intimate celebrations.",
  },
];

export const mockCategories = [
  {
    name: "Wedding Sarees",
    image: localAssets.wedding.url,
    count: 24,
  },
  {
    name: "Silk Sarees",
    image: localAssets.silk.url,
    count: 32,
  },
  {
    name: "Party Wear",
    image: localAssets.party.url,
    count: 18,
  },
  {
    name: "Cotton Sarees",
    image: localAssets.cotton.url,
    count: 45,
  },
  {
    name: "Daily Wear",
    image: localAssets.daily.url,
    count: 56,
  },
];

export const mockReviews: Review[] = [
  {
    _id: "r1",
    productId: "p1",
    name: "Priya Sharma",
    email: "priya@example.com",
    rating: 5,
    title: "Looks premium in person",
    comment:
      "The zari work has a rich finish and the saree came packed beautifully. It felt perfect for a family wedding.",
    date: "2026-05-12T10:30:00.000Z",
    verified: true,
  },
  {
    _id: "r2",
    productId: "p1",
    name: "Nisha Rao",
    rating: 5,
    title: "Heavy but comfortable",
    comment:
      "Loved the fall of the silk. The border looks elegant and the blouse color matched well.",
    date: "2026-05-08T14:10:00.000Z",
    verified: true,
  },
  {
    _id: "r3",
    productId: "p2",
    name: "Meera Patel",
    email: "meera@example.com",
    rating: 4,
    title: "Beautiful party wear",
    comment:
      "The shimmer is subtle and classy. I wish the product video was longer, but the saree quality is lovely.",
    date: "2026-05-15T09:45:00.000Z",
    verified: true,
  },
  {
    _id: "r4",
    productId: "p2",
    name: "Ritika S",
    rating: 5,
    title: "Easy to drape",
    comment:
      "Very light fabric and good for evening functions. The color looks graceful under warm lights.",
    date: "2026-05-05T17:20:00.000Z",
    verified: false,
  },
  {
    _id: "r5",
    productId: "p3",
    name: "Ananya Singh",
    rating: 4,
    title: "Soft daily saree",
    comment:
      "Comfortable for office wear and breathable through the day. The print is clean and simple.",
    date: "2026-05-11T12:00:00.000Z",
    verified: true,
  },
  {
    _id: "r6",
    productId: "p4",
    name: "Kavya Nair",
    rating: 5,
    title: "Festive and light",
    comment:
      "The saree has a soft flow and does not feel bulky. Good choice for puja and family functions.",
    date: "2026-05-13T16:40:00.000Z",
    verified: true,
  },
  {
    _id: "r7",
    productId: "p5",
    name: "Sonal Desai",
    rating: 5,
    title: "Classic silk look",
    comment:
      "The silk finish looks traditional without feeling outdated. Very nice for a reception.",
    date: "2026-05-09T08:25:00.000Z",
    verified: true,
  },
  {
    _id: "r8",
    productId: "p9",
    name: "Ishita Roy",
    rating: 4,
    title: "Good value",
    comment:
      "Nice cotton saree for casual use. Color is fresh and the fabric is easy to manage.",
    date: "2026-05-06T11:15:00.000Z",
    verified: false,
  },
  {
    _id: "r9",
    productId: "p6",
    name: "Tanvi Shah",
    rating: 4,
    title: "Neat office look",
    comment:
      "The linen feel is crisp and professional. It is easy to wear for long work days.",
    date: "2026-05-04T13:10:00.000Z",
    verified: true,
  },
  {
    _id: "r10",
    productId: "p7",
    name: "Pooja Menon",
    rating: 5,
    title: "Bridal finish is beautiful",
    comment:
      "The embroidery catches light very nicely. It feels grand without looking too loud.",
    date: "2026-05-16T18:30:00.000Z",
    verified: true,
  },
  {
    _id: "r11",
    productId: "p8",
    name: "Shruti Iyer",
    rating: 4,
    title: "Earthy and elegant",
    comment:
      "The texture has a handmade look and the color works well for daytime events.",
    date: "2026-05-07T15:05:00.000Z",
    verified: false,
  },
  {
    _id: "r12",
    productId: "p10",
    name: "Aditi Kapoor",
    rating: 5,
    title: "Reception ready",
    comment:
      "The organza is light and the border detail makes it look premium in photos.",
    date: "2026-05-18T10:50:00.000Z",
    verified: true,
  },
];

export const mockCoupons: Coupon[] = [
  {
    _id: "c1",
    code: "WELCOME10",
    type: "percentage",
    discount: 10,
    maxUses: 100,
    usedCount: 23,
    expiryDate: "2027-12-31",
    isActive: true,
    minimumOrder: 1000,
    applicableProducts: [],
    oneUsePerUser: true,
    usedBy: [],
  },
  {
    _id: "c2",
    code: "SAVE500",
    type: "fixed",
    discount: 500,
    maxUses: 50,
    usedCount: 12,
    expiryDate: "2027-10-31",
    isActive: true,
    minimumOrder: 2000,
    applicableProducts: [],
    oneUsePerUser: false,
    usedBy: [],
  },
  {
    _id: "c3",
    code: "SILK20",
    type: "percentage",
    discount: 20,
    maxUses: 30,
    usedCount: 8,
    expiryDate: "2027-09-30",
    isActive: true,
    minimumOrder: 3000,
    applicableProducts: ["p1", "p5", "p8"],
    oneUsePerUser: true,
    usedBy: ["oldbuyer@example.com"],
  },
  {
    _id: "c4",
    code: "OLDLOVE",
    type: "percentage",
    discount: 15,
    maxUses: 20,
    usedCount: 20,
    expiryDate: "2025-12-31",
    isActive: false,
    minimumOrder: 1500,
    applicableProducts: [],
    oneUsePerUser: true,
    usedBy: [],
  },
];

export const mockOrders: Order[] = [
  {
    _id: "o1",
    orderId: "VA10001",
    userEmail: "priya@example.com",
    customer: "Priya Sharma",
    phone: "9876543210",
    products: [
      {
        productId: "p1",
        title: "Kanjivaram Silk Bridal Saree",
        image: mockProducts[0]?.images?.[0] || "",
        price: 6999,
        quantity: 1,
      },
    ],
    shippingAddress: {
      fullName: "Priya Sharma",
      phone: "9876543210",
      address: "Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400050",
    },
    subtotal: 6999,
    couponCode: "WELCOME10",
    couponDiscount: 700,
    total: 6299,
    paymentMethod: "Razorpay",
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    date: "2026-05-10T11:20:00.000Z",
  },
  {
    _id: "o2",
    orderId: "VA10002",
    userEmail: "meera@example.com",
    customer: "Meera Patel",
    phone: "9123456780",
    products: [
      {
        productId: "p2",
        title: "Banarasi Georgette Party Saree",
        image: mockProducts[1]?.images?.[0] || "",
        price: 3299,
        quantity: 2,
      },
    ],
    shippingAddress: {
      fullName: "Meera Patel",
      phone: "9123456780",
      address: "Navrangpura",
      city: "Ahmedabad",
      state: "Gujarat",
      pincode: "380009",
    },
    subtotal: 6598,
    couponDiscount: 500,
    couponCode: "SAVE500",
    total: 6098,
    paymentMethod: "Razorpay",
    paymentStatus: "Paid",
    deliveryStatus: "Shipped",
    date: "2026-05-12T16:10:00.000Z",
  },
  {
    _id: "o3",
    orderId: "VA10003",
    userEmail: "ananya@example.com",
    customer: "Ananya Singh",
    phone: "9988776655",
    products: [
      {
        productId: "p3",
        title: "Cotton Handloom Daily Wear Saree",
        image: mockProducts[2]?.images?.[0] || "",
        price: 999,
        quantity: 1,
      },
    ],
    shippingAddress: {
      fullName: "Ananya Singh",
      phone: "9988776655",
      address: "Hazratganj",
      city: "Lucknow",
      state: "Uttar Pradesh",
      pincode: "226001",
    },
    subtotal: 999,
    couponDiscount: 0,
    total: 999,
    paymentMethod: "Razorpay",
    paymentStatus: "Pending",
    deliveryStatus: "Pending",
    date: "2026-05-14T09:45:00.000Z",
  },
];

export const mockCustomers: Customer[] = [
  {
    _id: "u1",
    name: "Priya Sharma",
    email: "priya@example.com",
    phone: "9876543210",
    totalOrders: 3,
    totalSpending: 18920,
    lastOrder: "2026-05-10T11:20:00.000Z",
  },
  {
    _id: "u2",
    name: "Meera Patel",
    email: "meera@example.com",
    phone: "9123456780",
    totalOrders: 2,
    totalSpending: 11098,
    lastOrder: "2026-05-12T16:10:00.000Z",
  },
  {
    _id: "u3",
    name: "Ananya Singh",
    email: "ananya@example.com",
    phone: "9988776655",
    totalOrders: 1,
    totalSpending: 999,
    lastOrder: "2026-05-14T09:45:00.000Z",
  },
];

export const mockTestimonials = [
  {
    name: "Priya Sharma",
    city: "Mumbai",
    rating: 5,
    comment:
      "The Kanjivaram saree looked exactly like the photos. Soft fabric, beautiful packaging, and quick delivery.",
    avatar: "PS",
  },
  {
    name: "Meera Patel",
    city: "Ahmedabad",
    rating: 5,
    comment:
      "Premium quality without the showroom pressure. The checkout was smooth and the saree felt special.",
    avatar: "MP",
  },
  {
    name: "Sunita Desai",
    city: "Pune",
    rating: 4,
    comment:
      "Great collection and elegant styling. I liked the fabric details and simple return policy.",
    avatar: "SD",
  },
];

export const videoStories = [
  {
    title: "Saree Walk",
    caption: "Fluid drapes and natural movement",
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    title: "Fabric Close-Up",
    caption: "Zari, texture, and soft hand-feel",
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    title: "Wedding Collection",
    caption: "Rich silks for the ceremony edit",
    video:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
];

export const mockAdminStats = {
  totalOrders: 1284,
  todayOrders: 23,
  pendingOrders: 47,
  deliveredOrders: 1102,
  totalRevenue: 4821500,
  totalProducts: 10,
  totalCustomers: 876,
  activeCoupons: 3,
  monthlyRevenue: [
    { month: "Jan", revenue: 320000, orders: 72 },
    { month: "Feb", revenue: 410000, orders: 84 },
    { month: "Mar", revenue: 380000, orders: 79 },
    { month: "Apr", revenue: 520000, orders: 104 },
    { month: "May", revenue: 490000, orders: 98 },
    { month: "Jun", revenue: 610000, orders: 121 },
  ],
  orderStatus: [
    { status: "Delivered", count: 1102 },
    { status: "Shipped", count: 89 },
    { status: "Pending", count: 47 },
    { status: "Cancelled", count: 46 },
  ],
};
